---
title: "EDRM 718 Assignment #10"
author: "Anna Ehrhorn"
date: "April 17, 2020"
output: html_notebook
---

*This assignment will focus on importing and wrangling data.*


***
#### Question 1

Import and initial tidying of the *Johnson Elementary Project Data*.

```{r}
library(here)
library(tidyverse)

johnson.elem.data <- read_csv(here("Data", 
                                   "Johnson Elementary ELA Project.csv"), 
                              skip = 4, 
                              col_names = c("Room", "ID", "Tardies;Absences",
                                            "Q1", "Q2", "Q3", "Q4"))
                      
johnson.elem.data
```


Further tidying of the *Johnson Elementary Project Data*.

```{r}
tidy.JElem.data <- johnson.elem.data %>% 
  fill(Room) %>%
  drop_na(Room:Q4) %>%
  separate('Tardies;Absences', 
           into = c("Tardies", "Absences"), sep = " ; ",
           convert = TRUE, extra = "drop", fill = "right")

tidy.JElem.data
```



***
#### Question 2

Summary Statistics for the Number of Tardies and Abseneces for each Room.

```{r}
summary.tard.abs <- tidy.JElem.data %>%
  group_by(Room) %>%
  summarize(Tardies_mean = mean(Tardies),
            Tardies_sd = sd(Tardies),
            Absences_mean = mean(Absences),
            Absences_sd = sd(Absences))

summary.tard.abs
```


***
#### Question 3

```{r}
freq.NAdata <- tidy.JElem.data %>%
  
  
```



***
#### Question 4



***
#### Question 5


